### ISSUE TITLE
Typo in setAllowedVarsions()

### ISSUE THREAD

**Issue by nikic** [paragonie/past#11]
https://github.com/paragonie/past/blob/89f9b32b73d9c45d2ddb3ff4dd000dddfd2c5777/src/Parser.php#L230 => Should be `setAllowedVersions()`.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/past/commit/c3b2a7fba0fe7e7e992229f9f545335703a5b387 - Thanks! I'm not sure how I missed that one.
