### ISSUE TITLE
Document Usage and Discourage Misuse

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/past#14]
I should make it explicit that neither PAST nor JWT are good solutions for some of the problems that developers try to use them for.

References:

* https://news.ycombinator.com/item?id=16073658
* https://news.ycombinator.com/item?id=16071179

**Comment by carnage** [comment]
One way to discourage misuse might be to drop the "enc" purpose. To me the major use case for that is stateless sessions

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/past/pull/24/commits/a6467c18500b16e506f1e4579cd500cf88bef8e6 will close this once #24 is ready.
