### ISSUE TITLE
Usage of 'version' might be confusing

### ISSUE THREAD

**Issue by danielx** [paragonie/past#17]
This is most likely a non issue but might be worth considering since one might think a greater version is always to be preferred.

**Comment by paragonie-scott** [comment]
Yes, that's worth considering.

> one might think a greater version is always to be preferred

That's always going to be the case with PAST.

For example, v1's public-key signatures are RSASSA-PSS. v2's is Ed25519. There's no room for foot-bullety ECDSA, nor for PKCS1v1.5. 

When it's time to define a version 3, it will most likely utilize [post-quantum cryptography](https://csrc.nist.gov/projects/post-quantum-cryptography/round-1-submissions). If a version is defined past this point, it will most likely be the result of decades of cryptanalysis that result in even better primitives and constructions, and consequently will be a definite upgrade.

**Comment by carnage** [comment]
In fact, when we originally discussed this spec; I suggested that a version 3 implementation would consider V1 tokens to be invalid/expired. eg it should only read tokens from Vn-1 of the spec

**Comment by paragonie-scott** [comment]
@carnage's comment is now formally declared here: https://github.com/paragonie/past/commit/e9cc1778433e490ee00a95088f42b5fc15f2db9e
