### ISSUE TITLE
Rename "publickey" to "tokenkey" in readme

### ISSUE THREAD

**Issue by carnage** [paragonie/past#2]
The term public key as used in the token specification is slightly confusing, I'd suggest renaming it to token key to better reflect it's usage.

eg

`version.purpose.tokenkey.ciphertext`

**Comment by paragonie-scott** [comment]
`tokenkey` might confuse people who do key identifiers too, though. (Tracking this feature request in #1)

Y'know how `sodium_crypto_box_seal()` prefixes the ephemeral public key, but the rest of it's basically `sodium_crypto_box()`? That prefixed public key is what we're doing here. Maybe `one-time-key` would work better?

**Comment by carnage** [comment]
It is what you are doing in protocol V2, but in V1 it is an RSA encrypted one-time random key. 

one-time-key may work best, has the side effect of promoting that it shouldn't be reused :p

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/past/commit/8eca298b1c2613d0d4ea54cec6ab41574bd8e06c :)

**Comment by paragonie-scott** [comment]
I forgot to press "close issue", but that's a better mistake than the converse (closing issues by accident, which could be received as rude).
