### ISSUE TITLE
Past does not rhyme with frost

### ISSUE THREAD

**Issue by timwis** [paragonie/past#25]
> Like the English word "pasta" without the final "a". It rhymes with "frost" and the first syllable in "roster".

I don't know about you, but in Philly, we pronounce frost as `frauwst` :P

**Comment by paragonie-scott** [comment]
:(

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/past/pull/24/commits/7e93e711b72347ba583fcddf299a7552b4cceafd

**Comment by timwis** [comment]
haha, I'm only teasing, though ironically the 2 words you added we also pronounce the `o` like `auw` :P

**Comment by paragonie-scott** [comment]
I mean, that's the idea. https://www.youtube.com/watch?v=_5A4kE5cdJ8
