### ISSUE TITLE
consider not adding padding for base64url encoding

### ISSUE THREAD

**Issue by fkooman** [paragonie/past#8]
Currently padding is used with the base64url encoding. It is a bit "nicer" not the have URL encoded `=` characters when using the tokens in URLs (query parameters). 

E.g. [PKCE](https://tools.ietf.org/html/rfc7636#appendix-A) and [JWS](https://tools.ietf.org/html/rfc7515) also use Base64 encoding without padding.

**Comment by paragonie-scott** [comment]
It looks like I already implemented this in the constant-time encoding library.

https://github.com/paragonie/constant_time_encoding/blob/61083df8887e7328a517580bc59880050aa03e30/src/Base64.php#L49-L60

The padding is defined in RFC 4648, but it should be OK to declare it "optional" and not include it by default in our implementation.

**Comment by sethbattin** [comment]
base64 defaults also include `'+'` and `'/'`, so using an alternate alphabet is required for url safety.  I don't know offhand of a php implementation of this, but I found this function to be a useful tactic (also i was interop'ing with python at the time i learned of this issue): https://docs.python.org/2/library/base64.html#base64.urlsafe_b64encode 
> Encode string s using the URL- and filesystem-safe alphabet, which substitutes - instead of + and _ instead of / in the standard Base64 alphabet.

ironically:
> The result can still contain =.

So perhaps make this lib remove all three chars?

**Comment by paragonie-scott** [comment]
> base64 defaults also include '+' and '/', so using an alternate alphabet is required for url safety.

We're already using Base64url as specified in RFC 4648.

**Comment by paragonie-scott** [comment]
This is done in https://github.com/paragonie/past/commit/1eaf3a854a56071d4bacb1fd2bbb7dbf65585fbe :)
